#!/bin/bash

# navigate to shared folder
cd /vagrant

if [ "$1" == "modules" ]; then
    echo "clearing and reinstalling /vagrant/node_modules"

    rm -r /vagrant/node_modules
    npm install --no-bin-links
fi