---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test]
  attributes: {}

- name: cacher-ng
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::cacher-ng]
  attributes: {}

- name: lwrps
  run_list:
  - recipe[minitest-handler]
  - recipe[apt_test::lwrps]
  attributes: {}
